name: Deploy React Site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build site
      run: npm run build

    - name: Ensure gh-pages branch exists
      run: |
        git fetch origin
        if git show-ref --quiet refs/heads/gh-pages; then
          echo "gh-pages branch exists."
        else
          echo "gh-pages branch does not exist. Creating it."
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initializing gh-pages branch"
          git push origin gh-pages
          git checkout main

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add -f build
        git commit -m 'Deploy to GitHub Pages' || true
        git push origin `git subtree split --prefix build main`:refs/heads/gh-pages --force
